#!/bin/sh

if [ $# -gt 0 ]; then
    threads=$1
else
    echo "bnchmark_vac_def nb-threads"
    exit
fi

lognumber=`cat ./bmnumber`

lognumber=`expr $lognumber + 1`

`echo "$lognumber" > ./bmnumber`

fullpath="/home/tcrain/my-school-work/concurrent/ver03Apr/concurrent/"

logvat="${fullpath}/logs/log_vac_step_at${lognumber}.txt"
logvrb="${fullpath}/logs/log_vac_step_rb${lognumber}.txt"

for j in \
    "1" \
    "2"
do

if [ "${j}" = "2" ]; then

threads=`expr $threads + 4`

fi

for i in \
    "1" \
    "2" \
    "3" \
    "4" \
    "6" \
    "8" \
    "10" \
    "12"
do

for vacconfig in \
    "-n2 -q90 -u98 -r1048576" \
    "-n4 -q60 -u90 -r1048576"
do

trans="4194304"
trans=`expr $trans \* $i`

echo "vacation_at_del -c${threads} ${vacconfig} -t${trans}" >> ${logvat}
echo "vacation_at_del -c${threads} ${vacconfig} -t${trans}"
exec ${fullpath}/vacation-0.9.10/vacation/vacation_at_del -c${threads} ${vacconfig} -t${trans} | tee -a ${logvat}

echo "vacation_at -c${threads} ${vacconfig} -t${trans}" >> ${logvrb}
echo "vacation_at -c${threads} ${vacconfig} -t${trans}"
exec ${fullpath}/vacation-0.9.10/vacation/vacation_at -c${threads} ${vacconfig} -t${trans} | tee -a ${logvrb}

done

done

done

exit