#!/bin/sh

if [ $# -gt 0 ]; then
    compid=$1
else
    compid=""
fi

lognumber=`cat ./bmnumber`

lognumber=`expr $lognumber + 1`

`echo "$lognumber" > ./bmnumber`

fullpath="/home/tcrain/my-school-work/concurrent/ver03Apr/concurrent/"

logvlowat="${fullpath}/logs/${compid}vac_def_low_at${lognumber}.txt"
logvhighat="${fullpath}/logs/${compid}vac_def_high_at${lognumber}.txt"
logvlowrb="${fullpath}/logs/${compid}vac_def_low_rb${lognumber}.txt"
logvhighrb="${fullpath}/logs/${compid}vac_def_high_rb${lognumber}.txt"

for threads in \
    "24"\
    "28" \
    "32" \
    "48"
do

for k in \
    "1" \
    "2"
do

if [ "${k}" = "1" ]; then
vacconfig="-n2 -q90 -u98 -r1048576"
logvat="${logvlowat}"
logvrb="${logvlowrb}"
else
vacconfig="-n4 -q60 -u90 -r1048576"
logvat="${logvhighat}"
logvrb="${logvhighrb}"
fi

for l in \
    "1" \
    "2"
do

trans="4194304"

#if [ ${threads} -gt 24 ]; then
#trans=`expr $trans \* 24`
#else
#trans=`expr $trans \* $threads`
#fi

trans=`expr $trans \* 12`

echo "vacation_at -c${threads} ${vacconfig} -t${trans}" >> ${logvat}
echo "vacation_at -c${threads} ${vacconfig} -t${trans}"
exec ${fullpath}/vacation-0.9.10/vacation/vacation_at -c${threads} ${vacconfig} -t${trans} | tee -a ${logvat}

echo "vacation_rb -c${threads} ${vacconfig} -t${trans}" >> ${logvrb}
echo "vacation_rb -c${threads} ${vacconfig} -t${trans}"
exec ${fullpath}/vacation-0.9.10/vacation/vacation_rb -c${threads} ${vacconfig} -t${trans} | tee -a ${logvrb}

done

done

done

exit