#!/bin/sh

if [ $# -gt 0 ]; then
    threads=$1
    shift;
if [ $# -gt 0 ]; then
    compid=$1
else
    compid=""
fi
else
    echo "exe threads (computer_id)"
fi

lognumber=`cat ./bmnumber`

lognumber=`expr $lognumber + 1`

`echo "$lognumber" > ./bmnumber`

fullpath="/home/tcrain/my-school-work/concurrent/ver03Apr/concurrent/"

logvlowat="${fullpath}/logs/${compid}vac_seq_low_atnb${lognumber}.txt"
logvhighat="${fullpath}/logs/${compid}vac_seq_high_atnb${lognumber}.txt"
logvlowrb="${fullpath}/logs/${compid}vac_seq_low_atnbdl${lognumber}.txt"
logvhighrb="${fullpath}/logs/${compid}vac_seq_high_atnbdl${lognumber}.txt"

for j in \
    "1"
do

for i in \
    "1" \
    "2" \
    "3" \
    "4" \
    "6" \
    "8" \
    "10" \
    "12" \
    "16" \
    "20"
do

for k in \
    "1" \
    "2"
do

if [ "${k}" = "1" ]; then

vacconfig="-n2 -q90 -u98 -r1048576"
logvat="${logvlowat}"
logvrb="${logvlowrb}"

else

vacconfig="-n4 -q60 -u90 -r1048576"
logvat="${logvhighat}"
logvrb="${logvhighrb}"

fi

trans="4194304"
trans=`expr $trans \* $i`

echo "vacation_atnb -c${threads} ${vacconfig} -t${trans}" >> ${logvat}
echo "vacation_atnb -c${threads} ${vacconfig} -t${trans}"
exec ${fullpath}/vacation-0.9.10/vacation/vacation_atnb -c${threads} ${vacconfig} -t${trans} | tee -a ${logvat}

echo "vacation_atnbdl -c${threads} ${vacconfig} -t${trans}" >> ${logvrb}
echo "vacation_atnbdl -c${threads} ${vacconfig} -t${trans}"
exec ${fullpath}/vacation-0.9.10/vacation/vacation_atnbdl -c${threads} ${vacconfig} -t${trans} | tee -a ${logvrb}

done

done

done

exit