#!/bin/bash

if [ $# -gt 2 ]; then
   firstpart1=$1
   shift;
   firstnum=$1
   shift;
   secondnum=$1
   shift;
else
    echo "suscript firstpart1 firstnum secondnum"
exit
fi

d="\$d"

gawk -f awk_scp_mb.awk ${firstpart1}log_micro_at${firstnum}.txt > at10
gawk -f awk_scp_mb.awk ${firstpart1}log_micro_at${secondnum}.txt > at20

gawk -f awk_scp_mb.awk ${firstpart1}log_micro_atnomaint${firstnum}.txt > atnomaint10
gawk -f awk_scp_mb.awk ${firstpart1}log_micro_atnomaint${secondnum}.txt > atnomaint20

gawk -f awk_scp_mb.awk ${firstpart1}log_micro_rb${firstnum}.txt > rb10
gawk -f awk_scp_mb.awk ${firstpart1}log_micro_rb${secondnum}.txt > rb20

gawk -f awk_scp_mbseq.awk ${firstpart1}log_micro_rbseq${firstnum}.txt > rbseq10
gawk -f awk_scp_mbseq.awk ${firstpart1}log_micro_rbseq${secondnum}.txt > rbseq20

gawk -f awk_scp_mbseq.awk ${firstpart1}log_micro_tfatseq${firstnum}.txt > tfatseq10
gawk -f awk_scp_mbseq.awk ${firstpart1}log_micro_tfatseq${secondnum}.txt > tfatseq20

gawk -f awk_scp_mbseq.awk ${firstpart1}log_micro_atseq${firstnum}.txt > atseq10
gawk -f awk_scp_mbseq.awk ${firstpart1}log_micro_atseq${secondnum}.txt > atseq20


