#!/bin/sh

if [ $# -gt 0 ]; then
    threads=$1
    shift;
if [ $# -gt 0 ]; then
    compid=$1
else
    compid=""
fi
else
    echo "bnchmark_vac_def nb-threads (computer_id)"
    exit
fi

lognumber=`cat ./bmnumber`

lognumber=`expr $lognumber + 1`

`echo "$lognumber" > ./bmnumber`

fullpath="/home/tcrain/my-school-work/concurrent/ver03Apr/concurrent/"

logvlowat="${fullpath}/logs/${compid}vac_step_low_at${lognumber}.txt"
logvhighat="${fullpath}/logs/${compid}vac_step_high_at${lognumber}.txt"
logvlowrb="${fullpath}/logs/${compid}vac_step_low_rb${lognumber}.txt"
logvhighrb="${fullpath}/logs/${compid}vac_step_high_rb${lognumber}.txt"

for j in \
    "1" \
    "2" \
    "3"
do

if [ "${j}" = "2" ]; then

threads=`expr $threads + 4`

fi

if [ "${j}" = "3" ]; then

threads=`expr $threads + 4`

fi

for i in \
    "1" \
    "2" \
    "3" \
    "4" \
    "6" \
    "8" \
    "10" \
    "12" \
    "16" \
    "20"
do

for k in \
    "1" \
    "2"
do

if [ "${k}" = "1" ]; then

vacconfig="-n2 -q90 -u98 -r1048576"
logvat="${logvlowat}"
logvrb="${logvlowrb}"

else

vacconfig="-n4 -q60 -u90 -r1048576"
logvat="${logvhighat}"
logvrb="${logvhighrb}"

fi


trans="4194304"
trans=`expr $trans \* $i`

echo "vacation_at -c${threads} ${vacconfig} -t${trans}" >> ${logvat}
echo "vacation_at -c${threads} ${vacconfig} -t${trans}"
exec ${fullpath}/vacation-0.9.10/vacation/vacation_at -c${threads} ${vacconfig} -t${trans} | tee -a ${logvat}

echo "vacation_rb -c${threads} ${vacconfig} -t${trans}" >> ${logvrb}
echo "vacation_rb -c${threads} ${vacconfig} -t${trans}"
exec ${fullpath}/vacation-0.9.10/vacation/vacation_rb -c${threads} ${vacconfig} -t${trans} | tee -a ${logvrb}

done

done

done

exit