#!/bin/bash

if [ $# -gt 2 ]; then
   firstpart1=$1
   shift;
   firstnum=$1
   shift;
   secondnum=$1
   shift;
else
    echo "suscript firstpart1 firstnum secondnum"
exit
fi

d="\$d"

gawk -f awk_scp_abr.awk ${firstpart1}log_micro_at${firstnum}.txt > abrat10
gawk -f awk_scp_abr.awk ${firstpart1}log_micro_at${secondnum}.txt > abrat20

gawk -f awk_scp_abr.awk ${firstpart1}log_micro_atnomaint${firstnum}.txt > abratnomaint10
gawk -f awk_scp_abr.awk ${firstpart1}log_micro_atnomaint${secondnum}.txt > abratnomaint20

gawk -f awk_scp_abr.awk ${firstpart1}log_micro_rb${firstnum}.txt > abrrb10
gawk -f awk_scp_abr.awk ${firstpart1}log_micro_rb${secondnum}.txt > abrrb20
